# Generated by Django 2.1.4 on 2019-01-08 06:57

from django.db import migrations
import djongo.models.fields
import kuotes.models


class Migration(migrations.Migration):

    dependencies = [
        ('kuotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kuote',
            name='source',
            field=djongo.models.fields.EmbeddedModelField(model_container=kuotes.models.Source, null=True),
        ),
    ]
