# Generated by Django 2.1.4 on 2019-01-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuotes', '0002_kuote_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Source URL')),
                ('image_url', models.URLField(verbose_name='Image URL')),
            ],
        ),
    ]
