# Generated by Django 2.1.4 on 2019-01-17 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kuotes', '0007_auto_20190117_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kuote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
